### ISSUE TITLE
About dialog is missing icon

### ISSUE THREAD

**Issue by hemraker** [warrenbuckley/Nucache.Explorer#3]
**Describe the bug**
About dialog is missing icon. Just has a text saying App Icon.

![screenshot_131](https://user-images.githubusercontent.com/3663619/43401451-78cbe178-9410-11e8-9b50-ab822a8577e5.png)

**To Reproduce**
1. Go to Help -> About
2. See error

**Expected behavior**
Expected to see the app icon in all it's glory

**Comment by warrenbuckley** [comment]
Yep all fixed for the 1.1.0 release as we didn't have an icon until this morning :)
